Repository nodadyoushutup/vulcan-utils, pull requests merged in 2024-04, with the labels that each got.

#1 [ADD] Workflow python-package
  .github/workflows/python-package.yml
Labels: enhancement

#2 [FIX] Update python-package action
  .github/workflows/python-package.yml
Labels: enhancement

#13 [FIX] README cleanup
  docs/README.md
  setup.py
Labels: enhancement

#14 [IMP] Private logger
  setup.py
  tests/test_logger.py
  vulcan_logger/logger.py
Labels: enhancement

#17 [ADD] Logger unit tests
  setup.py
  tests/test_logger.py
Labels: enhancement

#18 VLOG-5 [ADD] Pull request template
  .github/workflows/pull_request_validation.yml
  docs/pull_request_template.md
  setup.py
Labels: documentation

#20 VLOG-5_6
  .github/workflows/pull_request_validation.yml
Labels: documentation

#21 VLOG-9 [REL] Release 1.5.6
  .github/workflows/pull_request_validation.yml
  docs/pull_request_template.md
  setup.py
Labels: release

#22 VLOG-13 [ADD] Retry decorator
  tests/test_decorator.py
  vulcan_logger/decorator.py
Labels: enhancement

#23 VLOG-23 [REL] Release 1.6.0
  setup.py
  tests/test_decorator.py
  vulcan_logger/decorator.py
Labels: enhancement

#24 VLOG-22 [ADD] JSON decorator
  tests/test_decorator.py
  vulcan_logger/decorator.py
  vulcan_logger/encoder.py
Labels: enhancement

#25 Staging
  setup.py
  tests/test_decorator.py
  vulcan_logger/decorator.py
  vulcan_logger/encoder.py
Labels: release

#26 VLOG-28 [IMP] Infinite retry decorator
  .github/workflows/unit_tests.yml
  tests/test_decorator.py
  vulcan_logger/decorator.py
Labels: enhancement

#27 VLOG-31 [REL] Release 1.8.0
  .github/workflows/unit_tests.yml
  setup.py
  tests/test_decorator.py
  vulcan_logger/decorator.py
Labels: release

#28 VLOG-14 [ADD] Rate limit decorator
  tests/test_decorator.py
  vulcan_logger/decorator.py
Labels: enhancement

#29 VLOG-32 [REL] Release 1.9.0
  setup.py
  tests/test_decorator.py
  vulcan_logger/decorator.py
Labels: release

#30 VLOG-18 [ADD] Formatter & duration
  tests/test_formatter.py
  vulcan_logger/formatter.py
Labels: enhancement

#31 VLOG-11 [FIX] Renovate PR prefix
  .github/renovate.json
Labels: enhancement

#33 VLOG-38 [REL] Release 1.10.0
  .github/renovate.json
  setup.py
  tests/__init__.py
  tests/test_formatter.py
  tests/test_printable.py
  vulcan_logger/__init__.py
  vulcan_logger/formatter.py
  vulcan_logger/printable.py
Labels: release

#36 VLOG-41 [REL] Releave 1.10.1
  .github/workflows/pull_request_validation.yml
  docs/source/vulcan_logger.rst
  setup.py
Labels: release

#37 VLOG-39 [FIX] Unit test and encoder RTD
  docs/source/tests.rst
  docs/source/vulcan_logger.rst
Labels: documentation

#38 VLOG-42 [REL] Release 1.10.2
  docs/source/tests.rst
  docs/source/vulcan_logger.rst
  setup.py
Labels: release

#39 VLOG-16 [IMP] Rename to Vulcan Utils
  docs/README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/vulcan_logger.rst
  example/example.py
  tests/test_decorator.py
  tests/test_encoder.py
  tests/test_formatter.py
  tests/test_logger.py
  tests/test_printable.py
  vulcan_utils/__init__.py
  vulcan_utils/decorator.py
  vulcan_utils/encoder.py
  vulcan_utils/formatter.py
  vulcan_utils/logger.py
  vulcan_utils/printable.py
Labels: enhancement

#40 VUTIL-43 [REL] Release 1.11.0
  docs/README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/vulcan_logger.rst
  example/example.py
  setup.py
  tests/test_decorator.py
  tests/test_encoder.py
  tests/test_formatter.py
  tests/test_logger.py
  tests/test_printable.py
  vulcan_utils/__init__.py
  vulcan_utils/decorator.py
  vulcan_utils/encoder.py
  vulcan_utils/formatter.py
  vulcan_utils/logger.py
  vulcan_utils/printable.py
Labels: release

#41 VLOG-44 [FIX] ReadTheDocs modules
  docs/source/vulcan_utils.rst
Labels: documentation

#42 VUTIL-45 [REL] Release 1.11.1
  docs/source/vulcan_utils.rst
  setup.py
Labels: release

#43 VUTIL-30 [IMP] example.py
  .gitignore
  example.py
  example/example.py
  vulcan_utils/decorator.py
  vulcan_utils/encoder.py
  vulcan_utils/logger.py
  vulcan_utils/printable.py
Labels: documentation

#44 VUTIL-47 [REL] Release 1.11.2
  .gitignore
  example.py
  example/example.py
  setup.py
  vulcan_utils/decorator.py
  vulcan_utils/encoder.py
  vulcan_utils/logger.py
  vulcan_utils/printable.py
Labels: release

#45 VUTIL-33 [REF] Refactor Decorator
  example.py
  tests/test_decorator.py
  vulcan_utils/decorator.py
Labels: enhancement

#46 VUTIL-48 [REL] Release 1.11.3
  example.py
  setup.py
  tests/test_decorator.py
  vulcan_utils/decorator.py
Labels: release

#47 VUTIL [REL] Release 1.11.3
  setup.py
Labels: release

#48 VUTIL-3 [IMP] README
  docs/README.md
Labels: documentation

#49 VUTIL-50 [REL] Release 1.11.4
  docs/README.md
  setup.py
Labels: release

#50 VUTIL-3 [FIX] README
  docs/README.md
Labels: documentation

#51 VUTIL-51 [REL] Release 1.11.5
  docs/README.md
  setup.py
Labels: release

#52 VUTIL-52 [REL] Release 1.11.6
  docs/README.md
  setup.py
Labels: release

#54 VUTIL-53 [FIX] Decorator doc strings
  vulcan_utils/decorator.py
Labels: documentation

#55 VUTIL-54 [FIX] Pull request template
  docs/pull_request_template.md
Labels: documentation

#56 JIRA-40 [ADD] Commit message
  .github/workflows/commit_validation.yaml
  .github/workflows/pull_request_validation.yml
  docs/.gitmessage
Labels: enhancement

#57 VUTIL-55 [REL] Release 1.11.7
  .github/workflows/commit_validation.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/pull_request_validation.yml
  .github/workflows/unit_tests.yml
  docs/.gitmessage
  docs/pull_request_template.md
  setup.py
  vulcan_utils/decorator.py
Labels: release

#58 VUTIL-21 [ADD] Cache
  .github/workflows/unit_tests.yml
  docs/README.md
  docs/pull_request_template.md
  example.py
  requirements.txt
  tests/test_cache.py
  vulcan_utils/__init__.py
  vulcan_utils/cache.py
Labels: enhancement

#60 VUTIL-21 [FIX] Commit validation
  .github/workflows/commit_validation.yaml
Labels: enhancement

#59 VUTIL-56 [REL] Release 1.12.0
  .github/workflows/commit_validation.yaml
  .github/workflows/unit_tests.yml
  docs/README.md
  docs/pull_request_template.md
  example.py
  requirements.txt
  setup.py
  tests/test_cache.py
  vulcan_utils/__init__.py
  vulcan_utils/cache.py
Labels: release

#61 VUTIL-21 [FIX] RTD Cache module
  docs/source/vulcan_utils.rst
Labels: documentation

#62 VUTIL-57 [REL] Release 1.12.1
  docs/source/vulcan_utils.rst
  setup.py
Labels: release

#64 VUTIL-60 [REF] Decorator class deconstruction
  example.py
  tests/test_decorator.py
  vulcan_utils/decorator.py
Labels: enhancement

#65 VUTIL-62 [ADD] Pylint Github Action
  .github/workflows/pylint.yaml
  .github/workflows/unit_tests.yml
  requirements.txt
Labels: enhancement

#70 VUTIL-62 [ADD] Pylint Github Action
  .github/workflows/pylint.yaml
  .github/workflows/unit_tests.yml
  requirements.txt
Labels: enhancement

#72 VUTIL-62 [REF] Pylint rework
  example.py
  setup.py
  tests/__init__.py
  tests/test_cache.py
  tests/test_formatter.py
  update_version.py
  vulcan_utils/__init__.py
  vulcan_utils/cache.py
  vulcan_utils/decorator.py
  vulcan_utils/encoder.py
  vulcan_utils/formatter.py
  vulcan_utils/logger.py
  vulcan_utils/printable.py
Labels: enhancement

#73 VUTIL-64 [REL] Release 1.12.2
  .github/workflows/commit_validation.yaml
  .github/workflows/publish_pypi.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/pull_request_validation.yaml
  .github/workflows/pull_request_validation.yml
  .github/workflows/pylint.yaml
  .github/workflows/unit_tests.yaml
  .github/workflows/unit_tests.yml
  .github/workflows/yamllint.yaml
  .readthedocs.yaml
  .vscode/settings.json
  docs/README.md
  example.py
  requirements.txt
  setup.py
  tests/__init__.py
  tests/test_cache.py
  tests/test_decorator.py
  tests/test_formatter.py
  update_version.py
  vulcan_utils/__init__.py
  vulcan_utils/cache.py
  vulcan_utils/decorator.py
  vulcan_utils/encoder.py
  vulcan_utils/formatter.py
  vulcan_utils/logger.py
  vulcan_utils/printable.py
Labels: release

#74 VUTIL-65 [FIX] Renovate branch prefix
  .github/renovate.json
Labels: enhancement

#75 VUTIL-66 [REL] Release 1.12.3
  .github/renovate.json
  setup.py
Labels: release

#76 VUTIL-67 [FIX] License
  LICENSE
Labels: documentation
